defaults:
- algo: vae #flow
- object: basic
- _self_
- override hydra/launcher: joblib

hydra:
  launcher:
    # override the number of jobs for joblib
    n_jobs: 10

seed: 0

#gpu
gpu: [0]

# train hyperparameters
max_epoch: 200
batch_size: 128

num_train: 100000
num_test: 10000

lr: 0.0001
  
grad_clip_norm: 100.0

gamma: 0.998 # exp lr decay
every_n_epoch: 10


# BASIC
# - 004_sugar_box
# - 005_tomato_soup_can
# - 006_mustard_bottle
# - 024_bowl
# - 025_mug
# COMPLEX
# - 011_banana
# - 019_pitcher_base
# - 035_power_drill
# - 037_scissors
# - 051_large_clamp

# EXTRA
# - 002_master_chef_can
# - 003_cracker_box
# - 007_tuna_fish_can
# - 008_pudding_box
# - 009_gelatin_box
# - 010_potted_meat_can
# - 021_bleach_cleanser
# # - 036_wood_block # no possible grasps
# - 040_large_marker
# - 052_extra_large_clamp
# - 061_foam_brick